// Phase 6 acceptance — the oracle test (BUILD_PLAN):
// import both fixtures → apply the merges/roles/names from
// docs/examples/design.example.md → export. Unit-test the structure (section
// order) and the token set/resolutions; prose is checked by manual diff.

import { describe, expect, it } from "vitest";
import { parseStyleSnapExport } from "../../contract/schema";
import {
  ORACLE_ASSIGNMENTS,
  ORACLE_MERGES,
  ORACLE_NAMES,
  ORACLE_NOTES,
  oracleCaptures,
  oracleEffective,
  oracleRawTokens,
} from "../testing/oracle";
import { sanitizeNotes } from "./notes";
import { generateCleanedJson, generateDesignMd, type ExportInput } from "./index";
import { radiusInsight, spacingInsight, typeInsight } from "../insights";

/** Phase 10 — the export input the app assembles: confirmed review + derivation fills. */
function oracleExportInput(): ExportInput {
  const raw = oracleRawTokens();
  const effective = oracleEffective();
  const assignmentsObj = Object.fromEntries(effective.assignments);
  return {
    projectName: "Lumen",
    generatedAt: "2026-07-04T12:00:00Z",
    captures: oracleCaptures().map((c) => c.meta),
    rawTokenCount: raw.length,
    mergeCount: ORACLE_MERGES.length,
    tokens: effective.tokens,
    rawById: new Map(raw.map((t) => [t.id, t])),
    assignments: effective.assignments,
    names: ORACLE_NAMES,
    notes: ORACLE_NOTES,
    derived: effective.derived,
    unreviewedMerges: 0,
    spacingInsight: spacingInsight(effective.tokens, assignmentsObj),
    radiusInsight: radiusInsight(effective.tokens, assignmentsObj),
    typeInsight: typeInsight(effective.tokens, ORACLE_ASSIGNMENTS.get("type/body"), 1.25),
  };
}

describe("design.md export (FR-24) — the oracle", () => {
  const md = generateDesignMd(oracleExportInput());

  it("has the oracle's sections, in order", () => {
    const headings = md
      .split("\n")
      .filter((line) => line.startsWith("#"))
      .map((line) => line.replace(/^#+\s*/, ""));
    expect(headings).toEqual([
      "Lumen — Design System",
      "Rules for the coding agent",
      "Color",
      "Typography",
      "Foundations",
      "Components (derived from captures)",
      "Accessibility (computed)",
      "Mood & voice (author notes)",
      "Gaps — undefined in this system",
    ]);
  });

  it("header states the token accounting and both captures", () => {
    // 27 reviewed + 8 derived synthetics (active, focus, feedback ×3, link,
    // subheading, mono, shadow/lg) = 35 — secondary stays empty until opt-in.
    expect(md).toContain("40 raw tokens → 35 reviewed tokens (7 merges)");
    expect(md).toContain("`lumen.app` (browser extension)");
    expect(md).toContain("`Lumen Design v3` (Figma)");
    expect(md).toContain("Generated by StyleSnap on\n> 2026-07-04");
  });

  it("resolves every color role to the oracle's primitive and value", () => {
    const expectRow = (role: string, primitive: string, value: string) => {
      const row = md.split("\n").find((l) => l.startsWith(`| \`${role}\` |`));
      expect(row, role).toBeDefined();
      expect(row).toContain(`\`${primitive}\``);
      expect(row).toContain(`\`${value}\``);
    };
    expectRow("color/action/primary", "color/brand-blue", "#2E6BFF");
    expectRow("color/action/primary-hover", "color/brand-blue-deep", "#2456CC");
    expectRow("color/border/default", "color/gray-200", "#E4E7EC");
    expectRow("color/feedback/error", "color/red-600", "#D92D20");
    expectRow("color/surface/card", "color/white", "#FFFFFF");
    expectRow("color/surface/page", "color/gray-50", "#F9FAFB");
    expectRow("color/text/muted", "color/gray-500", "#667085");
    expectRow("color/text/primary", "color/ink", "#101828");
    // Secondary is opt-in (§2.41) — not filled by derivation alone.
    expect(md.split("\n").find((l) => l.startsWith("| `color/action/secondary` |"))).toBeUndefined();
  });

  it("renders the Figma scrim as ink @ 50%, distinct from text/primary", () => {
    const row = md.split("\n").find((l) => l.startsWith("| `color/surface/overlay` |"));
    expect(row).toContain("`color/ink` @ 50%");
    expect(row).toContain("`#101828` / 0.5");
  });

  it("notes the 5-way blue merge on the brand-blue primitive", () => {
    const row = md.split("\n").find((l) => l.startsWith("| `color/brand-blue` |"));
    expect(row).toContain("5-way merge");
    for (const hex of ["#2E6BFF", "#2E6CFF", "#2F6BFE", "#3067FF"]) {
      expect(row).toContain(hex);
    }
  });

  it("gradient stops reference color primitives (two-tier)", () => {
    const row = md.split("\n").find((l) => l.startsWith("| `gradient/hero` |"));
    expect(row).toContain("linear 135°");
    expect(row).toContain("`color/brand-blue` 0%");
  });

  it("typography: roles resolved, tracked-uppercase label kept as a primitive", () => {
    expect(md).toContain("| `type/display` | 48px / 700 / 1.1 |");
    expect(md).toContain("| `type/heading` | 30px / 600 / 1.2 |");
    expect(md).toContain("| `type/body` | 16px / 400 / 1.5 |");
    expect(md).toContain("| `type/caption` | 14px / 500 / 1.4 |");
    const label = md.split("\n").find((l) => l.includes("`type/label-uppercase`"));
    expect(label).toContain("*(primitive)*");
    expect(label).toContain("tracking 0.5px, uppercase");
    expect(md).toContain("Fonts: **Inter**, **ui-monospace**");
  });

  it("foundations: the full spacing scale, merge note, and shadow ramp", () => {
    expect(md).toContain(
      "`space/xs` 4 · `space/sm` 8 · `space/md` 16 · `space/lg` 24 · `space/xl` 32 · `space/2xl` 64",
    );
    expect(md).toContain("A 15px capture, 2×, was merged into `space/md` 16.");
    expect(md).not.toContain("A 12px value, 9×, is captured but **unassigned**");
    expect(md).toContain("*Scale intelligence: base ~4px.*");
    expect(md).toContain("*Scale intelligence: soft / rounded profile.*");
    expect(md).toContain("Type scale ratio: **×1.25**");
    expect(md).toContain("`radius/sm` 8");
    expect(md).toContain("`radius/md` 12");
    expect(md).toContain("`border-width/default` 1");
    expect(md).toContain("| `shadow/sm` |");
    expect(md).toContain("| `shadow/md` |");
    // Shadow colors resolve to the ink primitive at their opacity.
    expect(md).toContain("`color/ink` @ 5%");
    expect(md).toContain("`color/ink` @ 10%");
  });

  it("flags exactly the oracle's §Gaps — derivation cleared the derivable ones", () => {
    const gapsSection = md.split("## Gaps — undefined in this system")[1].split("---")[0];
    for (const gap of [
      "Breakpoints, z-index — never capturable",
      "**Motion** — no durations/easing specified (System notes field empty).",
      "**Voice & microcopy** — no tone/wording rules specified (System notes field empty).",
      "**Layout** — no container/grid notes specified (System notes field empty).",
    ]) {
      expect(gapsSection).toContain(gap);
    }
    // Derivation filled these — they must be GONE from §Gaps (FR-19).
    for (const cleared of [
      "`color/text/link`",
      "`type/mono`",
      "`color/action/primary-active`",
      "`color/border/focus`",
      "`color/feedback/success`",
      "`color/feedback/warning`",
      "`color/feedback/info`",
      "12px spacing captured but unassigned",
    ]) {
      expect(gapsSection).not.toContain(cleared);
    }
    // Secondary remains a recommended gap until the user opts in (§2.41).
    expect(gapsSection).toContain("`color/action/secondary`");
    // Notes gaps + never-capturable foundations + secondary.
    expect(gapsSection.split("\n").filter((l) => l.startsWith("- "))).toHaveLength(5);
  });

  it("derived values carry derivation provenance in the role tables (Phase 10)", () => {
    expect(md).toContain(
      "| `color/action/primary-active` | `color/0b42d5` | `#0B42D5` | derived from `color/brand-blue` — active (ΔL −0.12) |",
    );
    expect(md).toContain(
      "| `color/border/focus` | `color/brand-blue` | `#2E6BFF` |", // captured claim, normal provenance
    );
    expect(md).toContain("derived from `color/brand-blue` — feedback success");
    expect(md).toContain("derived — provenance in the roles table");
  });

  it("exports twice → byte-identical (determinism)", () => {
    expect(generateDesignMd(oracleExportInput())).toBe(md);
  });

  it("sketches the oracle's four components from capture groups (Phase 9a)", () => {
    const section = md.split("## Components (derived from captures)")[1].split("\n## ")[0];
    const lines = section.split("\n").filter((l) => l.startsWith("- "));
    expect(lines).toEqual([
      "- **Button** (`.btn-primary` / Figma `Button/Primary`): bg `color/action/primary` · radius `radius/sm` · hover → `color/action/primary-hover` · inner gap `space/xs`.",
      "- **Card** (`.card` / Figma `Card/Default`): bg `color/surface/card` · radius `radius/md` · shadow `shadow/sm` · padding `space/sm`.",
      "- **Input** (`.field`): border `border-width/default` `color/border/default`.",
      "- **Hero** (`.hero`): bg `gradient/hero` · padding `space/lg`/`space/xl` · title `type/display`.",
    ]);
  });

  it("computes the oracle's accessibility table — derived pairs included, all AA (Phase 9a/10)", () => {
    const section = md.split("## Accessibility (computed)")[1].split("\n## ")[0];
    const rows = section.split("\n").filter((l) => l.startsWith("| `") || l.startsWith("| w"));
    expect(rows).toEqual([
      "| `color/text/primary` on `color/surface/card` | 17.7:1 | ✅ |",
      "| `color/text/primary` on `color/surface/page` | 17.0:1 | ✅ |",
      "| `color/text/muted` on `color/surface/card` | 5.0:1 | ✅ |",
      "| `color/text/muted` on `color/surface/page` | 4.8:1 | ✅ |",
      "| `color/text/link` on `color/surface/card` | 4.9:1 | ✅ |",
      "| `color/text/link` on `color/surface/page` | 4.7:1 | ✅ |",
      "| white on `color/action/primary` | 4.5:1 | ✅ (no margin — avoid small text) |",
      "| white on `color/action/primary-hover` | 6.4:1 | ✅ |",
      "| white on `color/action/primary-active` | 7.6:1 | ✅ |",
      "| white on `color/feedback/success` | 4.5:1 | ✅ (no margin — avoid small text) |",
      "| white on `color/feedback/warning` | 4.6:1 | ✅ |",
      "| white on `color/feedback/error` | 4.8:1 | ✅ |",
      "| white on `color/feedback/info` | 4.7:1 | ✅ |",
    ]);
    expect(rows.every((r) => r.includes("✅"))).toBe(true);
  });

  it("template-filled notes confess their starter; a full fill leaves no notes gaps (FR-19b)", () => {
    const input = {
      ...oracleExportInput(),
      notes: {
        mood: "My own hand-written mood.",
        componentPrinciples: "Starter text.",
        motion: "Starter text with 150ms ease-out.",
        voice: "Starter text.",
        layout: "Starter text with breakpoints.",
      },
      noteSources: {
        mood: "user",
        componentPrinciples: "componentPrinciples/calm-saas",
        motion: "motion/calm-saas",
        voice: "voice/neobrutalist",
        layout: "layout/calm-saas",
      } as const,
    };
    const filled = generateDesignMd(input);
    // Hand-written text carries no suffix; template text confesses its starter.
    expect(filled).toContain("**Mood / vibe:** My own hand-written mood.\n");
    expect(filled).not.toContain('My own hand-written mood. *(from');
    expect(filled).toContain(
      '**Motion:** Starter text with 150ms ease-out. *(from the "Calm SaaS" starter — edit to taste)*',
    );
    expect(filled).toContain('*(from the "Neobrutalist" starter — edit to taste)*');
    // With every field filled, no notes gap-lines remain in §Gaps.
    const gaps = filled.split("## Gaps — undefined in this system")[1];
    expect(gaps).not.toContain("(System notes field empty)");
  });

  it("renders filled notes and marks the empty fields (Phase 9b)", () => {
    const section = md.split("## Mood & voice (author notes)")[1].split("\n## ")[0];
    expect(section).toContain("**Mood / vibe:** Fresh, trustworthy SaaS");
    expect(section).toContain("**Component principles:** surfaces are white cards");
    expect(section).toContain("**Motion:** *(not captured — see Gaps)*");
    expect(section).toContain("**Voice & microcopy:** *(not captured — see Gaps)*");
    expect(section).toContain("**Layout:** *(not captured — see Gaps)*");
  });

  it("Mood-only notes → Mood rendered, four empty-field gap lines (Phase 9b)", () => {
    const input = { ...oracleExportInput(), notes: { mood: "Bold and chunky." } };
    const only = generateDesignMd(input);
    expect(only).toContain("**Mood / vibe:** Bold and chunky.");
    const gaps = only.split("## Gaps — undefined in this system")[1];
    for (const label of ["Component principles", "Motion", "Voice & microcopy", "Layout"]) {
      expect(gaps).toContain(`**${label}** —`);
    }
    expect(gaps).not.toContain("**Mood / vibe** —");
    expect(generateDesignMd(input)).toBe(only); // still deterministic
  });

  it("every reviewed token appears by resolved name or role", () => {
    const input = oracleExportInput();
    const rolesByToken = new Map<string, string>();
    for (const [role, id] of input.assignments) rolesByToken.set(id, role);
    for (const token of input.tokens) {
      const label = rolesByToken.get(token.id) ?? ORACLE_NAMES.get(token.id);
      if (label) expect(md, token.id).toContain(`\`${label}\``);
    }
  });
});

describe("multi-role primitives (Phase 8 acceptance)", () => {
  it("one primitive backs two roles: two role rows, one primitives entry", () => {
    const input = oracleExportInput();
    // The team decides links use the brand blue too.
    input.assignments = new Map(ORACLE_ASSIGNMENTS).set("color/text/link", "ext_001");
    const md = generateDesignMd(input);

    const primary = md.split("\n").find((l) => l.startsWith("| `color/action/primary` |"));
    const link = md.split("\n").find((l) => l.startsWith("| `color/text/link` |"));
    expect(primary).toContain("`color/brand-blue`");
    expect(link).toContain("`color/brand-blue`");
    // The primitive is listed exactly once — one primitive, many uses.
    const primitiveRows = md.split("\n").filter((l) => l.startsWith("| `color/brand-blue` |"));
    expect(primitiveRows).toHaveLength(1);
    // And text/link is no longer a ROLE gap. (It now legitimately appears as
    // a Phase 9a contrast warning: brand-blue text on the gray-50 page
    // measures 4.3:1 — a real finding, not a regression.)
    const gaps = md.split("## Gaps")[1];
    expect(gaps).not.toContain("`color/text/link` — links");
    expect(gaps).toContain("`color/text/link` on `color/surface/page` — contrast 4.3:1 fails AA");
  });

  it("the ink primitive is referenced by text/primary AND surface/overlay", () => {
    // Straight from the oracle: overlay = ink @ 50%, text = ink — one entry.
    const md = generateDesignMd(oracleExportInput());
    const overlay = md.split("\n").find((l) => l.startsWith("| `color/surface/overlay` |"));
    const text = md.split("\n").find((l) => l.startsWith("| `color/text/primary` |"));
    expect(overlay).toContain("`color/ink` @ 50%");
    expect(text).toContain("`color/ink`");
    expect(md.split("\n").filter((l) => l.startsWith("| `color/ink` |"))).toHaveLength(1);
  });
});

describe("cleaned JSON export (FR-25)", () => {
  const cleaned = generateCleanedJson(oracleExportInput());

  it("round-trips through parseStyleSnapExport", () => {
    const result = parseStyleSnapExport(JSON.stringify(cleaned));
    expect(result.ok).toBe(true);
    if (result.ok) {
      expect(result.data.tokens).toHaveLength(35);
      expect(result.versionWarning).toBeUndefined();
    }
  });

  it("carries the derivation map for derived tokens (Phase 10)", () => {
    expect(cleaned.derivation).toBeDefined();
    const entry = cleaned.derivation!["derived_color_action_primary-active"];
    expect(entry).toEqual({
      derivedFrom: "ext_001",
      method: "active (ΔL −0.12)",
      edited: false,
    });
    // Only synthetic tokens appear; anchors/captured claims don't.
    expect(Object.keys(cleaned.derivation!).every((id) => id.startsWith("derived_"))).toBe(true);
  });

  it("populates merged/name on every token, provenance in meta", () => {
    expect(cleaned.tokens.every((t) => typeof t.name === "string" && t.name.length > 0)).toBe(true);
    const blue = cleaned.tokens.find((t) => t.id === "ext_001")!;
    expect(blue.merged).toBe(true);
    expect(blue.name).toBe("color/brand-blue");
    expect(blue.occurrences).toBe(36); // 18+3+1+2+12
    expect(blue.mergedFrom).toEqual(["ext_002", "ext_003", "ext_004", "fig_001"]);
    expect(cleaned.meta.figmaFile).toBe("Lumen Design v3");
    expect(cleaned.meta.pageUrl).toBe("https://lumen.app");
  });

  it("orders deterministically (type → role → name → value → id) and flags gaps", () => {
    expect(JSON.stringify(generateCleanedJson(oracleExportInput()))).toBe(
      JSON.stringify(cleaned),
    );
    const types = cleaned.tokens.map((t) => t.type);
    expect(types).toEqual([...types].sort(
      (a, b) =>
        ["color", "gradient", "typography", "spacing", "border-radius", "border-width", "shadow"].indexOf(a) -
        ["color", "gradient", "typography", "spacing", "border-radius", "border-width", "shadow"].indexOf(b),
    ));
    // Colors with roles come before role-less primitives, sorted by role.
    expect(cleaned.tokens[0].id).toBe("ext_001"); // color/action/primary
    expect(cleaned.gaps.length).toBe(5);
  });

  it("carries the filled System notes and round-trips them (Phase 9b)", () => {
    expect(cleaned.notes).toEqual(ORACLE_NOTES);
    // The `notes` key survives stringify → parse alongside the envelope.
    const raw = JSON.parse(JSON.stringify(cleaned)) as { notes?: unknown };
    expect(sanitizeNotes(raw.notes)).toEqual(ORACLE_NOTES);
    // And with nothing filled, the key is omitted entirely.
    const bare = generateCleanedJson({ ...oracleExportInput(), notes: {} });
    expect("notes" in bare).toBe(false);
  });

  it("unnamed tokens get the deterministic fallback name", () => {
    const violetless = cleaned.tokens.find((t) => t.id === "fig_004")!; // scrim, unnamed
    expect(violetless.name).toBe("color/101828-50");
  });
});
